---
- name: Create etcd user and group
  ansible.builtin.user:
    name: etcd
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Create etcd directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    group: etcd
    mode: "0755"
  loop:
    - /var/lib/etcd
    - /etc/etcd

- name: Download etcd archive
  ansible.builtin.get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: /tmp/etcd.tar.gz
    mode: "0644"

- name: Unarchive etcd
  ansible.builtin.unarchive:
    src: /tmp/etcd.tar.gz
    dest: /tmp
    remote_src: yes
    creates: "/tmp/etcd-v{{ etcd_version }}-linux-amd64"

- name: Install etcd binaries
  ansible.builtin.copy:
    src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
    remote_src: yes
  loop:
    - etcd
    - etcdctl
    - etcdutl

- name: Render etcd config
  ansible.builtin.template:
    src: etcd.conf.yml.j2
    dest: /etc/etcd/etcd.conf.yml
    owner: etcd
    group: etcd
    mode: "0644"
  notify: Restart etcd

- name: Install systemd unit for etcd
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/{{ etcd_service_name }}.service
    mode: "0644"
  notify: Daemon reload and restart etcd

- name: Enable etcd
  ansible.builtin.systemd:
    name: "{{ etcd_service_name }}"
    enabled: yes
    state: started

