---
- hosts: haproxy
  become: yes
  tasks:
    - name: Allow ports via UFW if present
      block:
        - ansible.builtin.command: ufw status
          register: ufw_status
          changed_when: false
          failed_when: false
        - when: "'Status: active' in ufw_status.stdout"
          block:
            - community.general.ufw: { rule: allow, port: "{{ item }}", proto: tcp }
              loop:
                - "{{ nginx_pg_write_listen | default(15432) }}"
                - "{{ nginx_pg_read_listen  | default(15433) }}"
                - "{{ nginx_stats_listen    | default(8080) }}"
            - ansible.builtin.command: ufw reload
              changed_when: false
      rescue: []
