all:
  hosts:
    vm-master:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
    vm-db1:
      ansible_host: 192.168.181.30
    vm-db2:
      ansible_host: 192.168.181.40
    vm-db3:
      ansible_host: 192.168.181.50

  children:
    pg_nodes:
      hosts:
        vm-db1:
        vm-db2:
        vm-db3:

    pg_lb:
      hosts:
        vm-master:

    infra:
      hosts:
        vm-master:

    pg_cluster:
      children:
        pg_nodes:
        pg_lb:
