---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ apt_packages_common }}"
    state: present

- name: Install PostgreSQL packages
  ansible.builtin.apt:
    name: "{{ apt_packages_pg }}"
    state: present
