---
# Кластер: etcd + patroni + (кластерный) nginx/haproxy на pg_lb
# Запуск: ansible-playbook -i inventory/hosts.yml playbooks/pg-cluster/cluster.yml

- name: Etcd for Patroni DCS
  hosts: etcd
  gather_facts: yes
  become: yes
  roles:
    - role: common
    - role: etcd
  tags: [etcd]

- name: PostgreSQL nodes with Patroni
  hosts: pg_nodes
  gather_facts: yes
  become: yes
  roles:
    - role: common
    - role: patroni
  tags: [patroni,postgres]

- name: PG load balancer + stats UI
  hosts: pg_lb
  gather_facts: yes
  become: yes
  roles:
    - role: haproxy    # балансер для PG (15432/15433)
    - role: nginx      # только pg-stats/streams
  tags: [pg_lb,balancer,nginx]
